#define APPNAME                      "Bbp"

/* String maximum sizes. */
#define MAX_ABOUT_STRING             10
#define MAX_APPNAME_STRING           20
#define MAX_MENU_STRING              20
#define MAX_TITLE_STRING             20

/* String table constant ids. */
#define IDS_APPNAME                   1
#define IDS_TITLE                     2
#define IDS_ABOUT                     3
#define IDS_MENU                      4

/* Main menu bar ids. */
#define IDM_EXIT                    101
